//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthwindService
{
    using System;
    using System.Collections.Generic;
    
    public partial class DecimalPlaceTest
    {
        public int id { get; set; }
        public Nullable<decimal> rand_decimal { get; set; }
        public Nullable<decimal> rand_number { get; set; }
        public string rand_string { get; set; }
    }
}
