//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthwindService
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTerritories_Multi_FK
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int EmployeeID_FK { get; set; }
        public string TerritoryID_FK { get; set; }
    
        public virtual EmployeeTerritory EmployeeTerritory { get; set; }
    }
}
