//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthwindService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Space_Table
    {
        public int Primary_Key { get; set; }
        public string Space_Property { get; set; }
        public string Space_Property1 { get; set; }
        public string Emp_Name { get; set; }
        public string Emp_Name1 { get; set; }
        public string Emp_Name2 { get; set; }
        public string Emp_Name3 { get; set; }
    }
}
